- name: Upgrade the system
  dnf:
    name: "*"
    state: latest
  tags:
    - dnf
    - upgrade

# disabled because maybe i dont want to reboot the system after dnf upgrade...
# maybe, just maybe i will use dnf upgrade but dont bother to reboot because i
# will reboot some time after that.......................... better have them
# split

# check if the system requires a reboot
#- import_tasks:
#file: generic/dnf-requires-reboot.yaml
