- name: Reload udev
  shell: # maybe i should use command module...
    cmd: udevadm control --reload-rules && udevadm trigger /etc/udev/rules.d/* 2>/dev/null
  become: true
  ignore_errors: true # so it wont fail with `--check` or for some any other reason;
# maybe i should do it in a block and do rescue thing?

- name: Restart sshd
  systemd_service:
    state: restarted # i think its not 'reloaded'
    name: sshd
