---
- name: install RPMFusion repository
  import_tasks:
    file: rpmfusion-setup.yaml
  tags:
    #- nonfree
    - rpmfusion
    - postinstall
    - dnf

- name: install codecs and drivers
  import_tasks:
    file: codecs-and-drivers.yaml
  when: hardware_setup
  notify: reboot            # the better solution would be to tag only codec installations but im lazy
  tags:
    - postinstall
    - dnf
    - gpu

- name: install psutil library for ansible dconf module
  dnf:
    name: python3-psutil
    state: present
  when: kefir


- when: gnome_suspend_disable
  block:
  - name: disable GNOME suspend on AC
    copy:
      src: gnome-suspend-ac
      dest: /etc/dconf/db/local.d/11-gnome-disable-ac-suspend.dconf
    register: dconf_update # maybe do a notifier here?
    notify: reboot # because GDM

  - name: update dconf (should be a handler i think :))
    command:
      cmd: dconf update
    when: dconf_update.changed
