# TODO: hybrid graphics
# this thing should always be invoked with "gpu" tag... 
# it shoult be invoked with this tag from a higher level

- name: Parse GPU
  shell: lspci -vmm | grep -A1  "VGA compatible controller" | grep -v "^Class:" | cut -d ':' -f 2-  | tr -d '\t' | grep -v "^--" | cut -d ' ' -f 1 | tr '[:upper:]' '[:lower:]' | sort -u | tr -d '\n'
  register: gpu
  changed_when: false
  check_mode: no

- set_fact:
    gpu={{ gpu.stdout }}

- name: print out GPU model
  debug:
    msg: "{{ gpu }}"

- when: gpu  == "nvidia" # nvidia block
  block:
  - name: Install NVIDIA proprietary driver and applications
    dnf:
      name:
        - akmod-nvidia
        - xorg-x11-drv-nvidia-cuda
        - nvidia-settings
      state: present
      register: nvidiainstall # used for rebooting few lines ahead
  
  - name: Install hardware codecs (NVIDIA)
    dnf:
      name:
        - sudo dnf install libva-nvidia-driver.i686
        - sudo dnf install libva-nvidia-driver.x86_64
      register: codecsinstall # unused(?)
  
    #file:

# nvidia block is over

- name: Install Intel codecs
  dnf:
    name:
      - intel-media-driver
      - libva-intel-driver
  when: gpu == "intel"
  register: codecsinstall

# https://github.com/ansible/ansible/issues/29857
# requires testing!!! didnt test anything on AMD machines
# TODO: swapping block -- i mean i dont even have a amd gpu
- name: Install AMD codecs
  shell: |
    dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld;
    dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld;
    dnf swap -y mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686
    dnf swap -y mesa-vdpau-drivers.i686 mesa-vdpau-drivers-freeworld.i686
  when: gpu == "advanced"
  register: codecsinstall

- block:
  - name: swap ffmpeg if neccessary
    shell: |
      dnf swap -assumeno ffmpeg-free ffmpeg | grep -qe 'Nothing to do.'
    register: ffmpeg_swap
    ignore_errors: true
    changed_when: "'Nothing to do.' not in ffmpeg_swap.stdout"
    failed_when: false

# this thing replaced
#dnf update -y @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

  - name: Install codecs (via updating multimedia group)
    dnf:
      name: '@multimedia'
      state: latest         # no upgrade tag because... too much cruft
      exclude: PackageKit-gstreamer-plugin
      install_weak_deps: false

# end of ffmpeg swap saga

- name: Install complement packages from @sound-and-video
  dnf:
    name: '@sound-and-video'
    state: latest # i dont think that "present" will do anything here, so ill just leave it as it
    #when: codecsinstall.changed # i disabled it because sytsem configuration might change
    # imperatively and maybe, just MAYBE this thing can hit and do changes from that

- import_tasks:
    file: generic/reboot.yaml # dont need dnf to check that :)
# tags:
#   - reboot

    # why reboot here? because flatpak can weirldy NOT react to system
    # libraries being change and require a reboot to properly install runtimes :\
