- block:
  - name: Add the flathub flatpak repository remote to the system installation
    community.general.flatpak_remote:
      name: flathub
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present

  - name: Enable flathub remote
    community.general.flatpak_remote:
      name: flathub
      state: present
      enabled: true

  tags:
    - flathub
    # no flatpak here because flatpak is for flatpak app installation skip :)

