- block:
  - name: Add the RPMFusion repository keys
    ansible.builtin.rpm_key:
      key: "{{ item }}"
      state: present
    with_items: 
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

  - name: Add the RPMFusion repositories
    dnf:
      name:
      - 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm'
      - 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm'
      state: present
    when: ansible_distribution == 'Fedora'

  tags:
    - dnf
    - rpmfusion

- name: Refresh PackageKit
  ansible.builtin.dnf:
    name: '@core'
    state: latest
  tags:
    - dnf
    - rpmfusion
    - upgrade # because it actually upgrades the system
