# originally i made it interactive but was jank and its tagged, so you can just
# skip it with `--skip-tags`, so why bother making it interactive?

- name: Copy drop-in ssh config
  copy:
    src: openssh-fedora-workstation.conf
    dest: /etc/ssh/sshd_config.d/06-ansible-fedora-workstation.conf
    backup: false
    force: true
    mode: "0600"
  notify: Restart sshd
