# Main task

- name: collect facts about system services :) #originally was used for checking sshd for dnf reboot
  service_facts:

- import_tasks:
    file: postinstall/flathub-setup.yaml
  tags:
    - postinstall
    - flathub
    #- flatpak why flatpak is not here? because i want to add the repo and thats it

- block:      # dnf upgrade and check for reboot
  - import_tasks:
      file: generic/dnf-upgrade.yaml
    tags:
      - dnf
      - upgrade

  - import_tasks:
      file: generic/dnf-requires-reboot.yaml
    tags:
      - dnf
      - reboot

- block:
  - name: Set up RPMFusion
    import_tasks:
      file: postinstall/rpmfusion-setup.yaml
    tags:
      - postinstall
      - rpmfusion
      - dnf

  - name: Setup drivers and codecs
    import_tasks:
      file: postinstall/codecs-and-drivers.yaml
    tags:
      - postinstall
      - rpmfusion
      - gpu
      - dnf

- block:            # dont tag these :)
  - import_tasks:
      file: system-setup.yaml
  - import_tasks:
      file: user-setup.yaml
    tags:
      - home # this should be the only place this tag is used
  tags:
    - personal
