# personal system setup task to create and manage users with their local setup,
# edit `user-setup.yaml` file
# DO NOT tag anything with "personal" because it inherits this tag

- block: # dnf block; tag is at the bottom
  - name: install storage utilites
    dnf:
      name:
      - smartmontools
      - scrub
      - hdparm
      - testdisk
      - ecryptfs-utils
      - ddrescue
      state: present
  
  - name: cmdline and system utilites
    dnf:
      name:
      - vifm
      - ncdu
      - moreutils
      - renameutils
      - zstd
      - bsdtar
      - busybox
      - tree
      - rsync
      - htop
      - android-tools
      - lm_sensors
      - xev
      - wev
      - steam-devices
      - xdelta
      - xsel
      - wl-clipboard
      - openssl
      - axel
      - monitor-edid edid-decode
      state: present
  
  - name: development stuff
    dnf:
      name:
        - gcc
        - bandit
      state: present
  
  - name: GUI utilites (mostly GNOME)
    dnf:
      name:
      - wireshark
      - file-roller
      - dconf-editor
      - gnome-tweaks
      - pdfarranger
      - file-roller-nautilus
      - ghex
  
  - name: network tools
    dnf:
      name:
        - nmap
        - whois
        - ngrep
      state: present
  
  - name: multimedia packages
    dnf:
      name:
        - celluloid
        - obs-studio
        - yt-dlp
      state: present
  
  - name: dnf stuff
    dnf:
      name:
        - yum-utils
      state: present
  
  - name: documentation packages
    dnf:
      name:
        - man-pages-posix
      state: present
  
  - name: fancy stuff
    dnf:
      name:
        - lolcat
        - neofetch
        - fastfetch
        - vrms-rpm
        - rbanffy-3270-fonts
      state: present
  
  # do i really need git-lfs?
  
  - name: git stuff
    dnf:
      name:
        - git
        - git-lfs
        - gh
      state: present
  
  - name: shells
    dnf:
      name:
        - fish
        - dash
      state: present
  
  - name: text editor
    dnf:
      name:
        - neovim
        - vim
      state: present
  
  - name: containers
    dnf:
      name:
        - podman
        - podman-compose
        - distrobox
      state: present
  
  - name: virtualization
    dnf:
      name:
        - virt-install
        - guestfs-tools
        - libvirt
        - virt-manager
        - virt-install
        #- VirtualBox
      state: present
  
  - name: ansible
    dnf:
      name:
        - ansible
        - ansible-collection-community-general
  
  - name: fedora backgrounds
    dnf:
      name:
        - f32-backgrounds-gnome
        - f33-backgrounds-gnome
        - f34-backgrounds-gnome
        - f37-backgrounds-gnome
      state: present

  - name: install legacy dnf4 if its fedora 41 and latter
    when: ansible_facts['distribution_major_version'] | int > 40
    dnf:
      name:
        - dnf4
      state: present
  
  - name: swap nano with vim as default editor # i think this will even remove nano :)
    shell: |
      dnf swap -y nano-default-editor vim-default-editor
    register: editor_swap
    changed_when: "'Nothing to do.' not in editor_swap.stdout"


  tags:
    - dnf # no personal tag because its invoked with it
#
# end of dnf block :)

- block: # copr and custom repositories

  - name: Enable Fedora copr for ghostty
    community.general.copr:
      name: pgdev/ghostty
      state: enabled

  - name: install ghostty
    dnf:
      name: ghostty
      state: present

  tags:
    - dnf

# end of dnf copr and custom repositories block


## flatpak part
- block:
  - name: install Flatpak applications
    community.general.flatpak:
      name: "{{ item }}"
      state: present
      method: system
      remote: flathub
    loop:
        - com.github.neithern.g4music
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.valvesoftware.Steam
        - im.riot.Riot
        - io.github.ungoogled_software.ungoogled_chromium
        - org.kde.konsole
        - org.kde.krita
        - org.kde.okular
        - org.keepassxc.KeePassXC
        - org.prismlauncher.PrismLauncher
        - org.qbittorrent.qBittorrent
        - org.telegram.desktop
        - com.github.johnfactotum.Foliate
        - org.nomacs.ImageLounge
        - io.gitlab.librewolf-community

  tags:
    - flatpak
    - flathub
#
# end of flatpak block :)

- name: EXPERIMENTAL sshd setup
  import_tasks:
    file: postinstall/sshd-setup.yaml
  tags:
    - ssh
    - experimental
    - never # because its experimental :)

- name: disable GNOME software automatic updates
  block:
    - copy:
        src: gnome-software
        dest: /etc/dconf/db/local.d/12-gnome-software.dconf # why twelve tho
        mode: '0644'
        backup: no
        # maybe a gnome tag here....
      register: dconf_update # maybe do a notifier here?

    - command:
        cmd: dconf update
      when: dconf_update.changed

# end of block

- name: enable networkmanager opportunistic dns over tls
  ansible.builtin.copy:
    src: networkmanager-dot.conf
    dest: /etc/NetworkManager/conf.d/90-dnf-over-tls.conf
    mode: '0644'
    backup: no
  tags:
    - security

- name: fix IBM SpaceSaver II scrolling on Wayland # experimental!!
  copy:
    src: ibm-spacesaver-ii-scrolling.rules
    dest: /etc/udev/rules.d/12-ibm-spacesaver-ii-scrolling.rules
    mode: '0644'
    backup: no
  notify: Reload udev
  tags:
    - experimental    # i enable it because it shouldnt break anything...
    #- never

# check if the system requires a reboot
- import_tasks:
    file: generic/dnf-requires-reboot.yaml
  tags:
    - reboot
