- name: reload udev
  shell: # maybe i should use command module...
    cmd: |
      udevadm control --reload-rules && udevadm trigger /etc/udev/rules.d/*
  become: true
  ignore_errors: true # so it wont fail with `--check` or for some any other reason;
# maybe i should do it in a block and do rescue thing?

- name: restart sshd
  systemd_service:
    state: restarted # i think its not 'reloaded'
    name: sshd

- name: restart and enable libvirtd service
  systemd:
    name: libvirtd
    state: restarted
    enabled: true
  listen:
    - restart libvirtd

  tags:
    - virtualization

- name: fc-cache
  command:
    cmd: fc-cache
  ignore_errors: true
