# scrapped stuff

# coulda use templates but whatever :)
# todo: fix the # ANSIBLE marker blocks
# btw SELinux attrs are ok :)
# btw the file would be clean from #ANSIBLE blocks when you change it (for
# example, changing the user picture)
- name: change language to Russian for nonexisting user 
  tags: [ never, testing ]
  blockinfile:
    backup: false
    create: true
    append_newline: false
    prepend_newline: false
    mode: "0644" # for some reason GNOME sets it to 0644, yet the file for first user is "0600"
    owner: root
    path: /var/lib/AccountsService/users/ivan
    block: |
      [User]
      Languages=ru_RU.UTF-8;

- name: manage placeholder user that doesnt exist
  become_user: "testing"
  tags: [ never, testing ]
  block:
    - name: set GNOME dark style
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "prefer-dark"
        state: present
      ignore_errors: true # because it might fail in a weird way

    - name: manage btrfs subvolumes in $HOME
      community.general.btrfs_subvolume:
        name: "{{ item }}"
      loop:
        - /home/"{{ main_user }}/Music/collection"   # TODO: test this thing... i doubt that `~` will work
        - /home/"{{ main_user }}/.local/share/libvirt/images"
      ignore_errors: true # why? because it might break if the directories already exist. fix it manually yourself :) TODO: btrfs subvol migration
      tags:
        - btrfs
        - postinstall # tagging this explicitly
