---
# Main task
#- name: collect facts about system services :) #originally was used for checking sshd for dnf reboot
#service_facts:

# these two are separate because
# its easier to edit multiple lists of packages
# rather than one big messy file

- import_tasks:  # dnf packages
    file: dnf-install.yaml
  when: install_packages
  tags:
    - dnf
    - personal

- import_tasks:
    file: user-setup.yaml
  when: setup_home
  tags:
    - home
    - personal

- import_tasks: # apply my system-level tweaks
    file: iamcrazy.yaml
  when: apply_nifty_hacks
  become: true    # explicit become because... reasons
  tags:
    - experimental # duh...
    - personal

- import_tasks:
    file: flatpak-install.yaml
  when: install_flatpaks
  tags:
    - flathub # i mean...
    - flatpak
    - personal


    # after running this, i highly recommend to run a reboot :)
