# DO NOT tag anything with "personal" because it inherits this tag
# also same applies to "home" tag. dont tag it :)

- name: manage my user-local configuration :)
  become_user: "{{ main_user }}"
  block:
    - name: fetch podman container images
      tags:
        - podman
      ignore_errors: true
      containers.podman.podman_image:
        name: "{{ item }}"
        state: present
      loop:
        - debian:12
        - opensuse/tumbleweed:latest
        - fedora:latest

    - name: manage btrfs subvolumes in $HOME
      community.general.btrfs_subvolume:
        name: "{{ item }}"
      loop:
        - ~/Music/collection    # TODO: test this thing... i doubt that `~` will work
        - ~/.local/share/libvirt/images
      ignore_errors: true # why? because it might break if the directories already exist. fix it manually yourself :) TODO: btrfs subvol migration
      tags:
        - btrfs
        - postinstall # tagging this explicitly

    - name: ensure that CoW is disabled on libvirt's `images` directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        attributes: '+C'
      loop:
        - ~/.local/share/libvirt/images

    - name: create directories i # funni, iso, git\github
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/Desktop/github
        - ~/Desktop/git
        - ~/Pictures/funni
        - ~/Pictures/wallpapers
        - ~/Videos/funni
        - ~/.local/share/fonts

    - name: manage directories with CoW disabled
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        attributes: '+C'
      loop:
        - ~/Downloads/iso
        - ~/Downloads/torrent
        - ~/Videos/torrent
        - ~/Music/torrent

    - name: download and install Spleen font
      unarchive:
        remote_src: true
        src: 'https://github.com/fcambus/spleen/releases/download/2.1.0/spleen-2.1.0.tar.gz'
        dest: ~/.local/share/fonts/
        include: ["*.otf", "*.otb"]
      retries: 5
      delay: 10
      notify: fc-cache

    - name: fetch git repos with configs :)
      git:
        clone: true
        force: false # idk... do it yourself
        update: true
        repo: https://github.com/allpower2slaves/dotfiles.git
        dest: ~/Desktop/github/dotfiles
      ignore_errors: true
      tags:
        - git

    - name: make symlinks and apply the config files
      file:
        src: "~/Desktop/github/dotfiles/{{ item }}"
        dest: "~/.config/{{ item }}"
        force: false    # nah :)))))
        state: link
      ignore_errors: true     # why? because symlinking may literally fail. i dont want to force rm firectories with ansible :)
      loop:
        - nvim
        - mpv
        - fish
        - ghostty

    - name: apply GNOME setup
      include_tasks:
        file: gnome-setup.yaml
      when: gnome_setup

    - name: (dirty) apply generic cross-system GNOME settings # DEPRECATED
      shell:
        cmd: |
          dconf load / < ~/Desktop/github/dotfiles/gnome-setup.dconf
      when: 0 > 32
      tags:
        - experimental
        - never

    - name: Make fedora-based texlive container for distrobox # maybe i should switch to alpine?
      containers.podman.podman_image:
        state: build
        name: fedora-texlive-distrobox
        build:
          cache: true
          container_file: |-
            FROM fedora:latest
            RUN dnf install -y texlive-scheme-full
            RUN dnf --setopt "install_weak_deps=False" install -y fish
      tags:
        - podman
        - latex # do i even need this tag at all
        - never # i dont care.... i dont care................. :)

# end of block
