# first block -- create users and manage them on system level
# latter blocks -- user-local configuration with `become:`
# DO NOT tag anything with "personal" because it inherits this tag
# also same applies to "home" tag. dont tag it :)
 
- name: create family group
  group:
    name: family
    state: present
    gid: 1100         # i dont want to bother with uid-gid collision :)

- name: add main user to family group
  user:
    name: "{{ main_user }}"
    groups:
      - family
    append: yes

- name: create a non-CoW directory for Steam games outside of ~/
  file:
    path: /opt/steam
    attributes: '+C'
    mode: '0775'
    state: directory
    owner: "{{ main_user }}"
    group: family

# system-level setup part ends here

- name: manage my user-local configuration :)
  become_user: "{{ main_user }}"
  block:
    - name: fetch podman container images
      tags:
        - podman
      ignore_errors: true
      containers.podman.podman_image:
        name: "{{ item }}"
        state: present
      loop:
        - nginx: latest # debug
        - debian:12
        - opensuse/tumbleweed:latest
        - fedora:latest

    - name: create directories i # funni, iso, git\github
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/Desktop/github
        - ~/Desktop/git
        - ~/Pictures/funni
        - ~/Pictures/wallpapers
        - ~/Videos/funni

    - name: create directories with CoW disabled
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        attributes: '+C'
      loop:
        - ~/Downloads/iso
        - ~/Downloads/torrent
        - ~/Videos/torrent
        - ~/Music/torrent

    - name: fetch git repos with configs :)
      git:
        clone: true
        force: true
        update: true
        repo: https://github.com/allpower2slaves/dotfiles.git
        dest: ~/Desktop/github/dotfiles
      ignore_errors: true
      tags:
        - git

    - name: make symlinks and apply the config files
      file:
        src: "~/Desktop/github/dotfiles/{{ item }}"
        dest: "~/.config/{{ item }}"
        force: true
        state: link
      ignore_errors: true     # why? because symlinking may literally fail. i dont want to force rm firectories with ansible :)
      loop:
        - nvim
        - mpv
        - fish
        - ghostty

    - name: Make fedora-based texlive container for distrobox # maybe i should switch to alpine?
      containers.podman.podman_image:
        state: build
        name: fedora-texlive-distrobox
        build:
          cache: true
          container_file: |-
            FROM fedora:latest
            RUN dnf install -y texlive-scheme-full
            RUN dnf --setopt "install_weak_deps=False" install -y fish
      tags:
        - podman
        - latex # do i even need this tag at all
# end of block


# coulda use templates but whatever :)
# todo: fix the # ANSIBLE marker blocks
# btw SELinux attrs are ok :)
# btw the file would be clean from #ANSIBLE blocks when you change it (for
# example, changing the user picture)
- name: change language to Russian for nonexisting user 
  tags: [ never, testing ]
  blockinfile:
    backup: false
    create: true
    append_newline: false
    prepend_newline: false
    mode: "0644" # for some reason GNOME sets it to 0644, yet the file for first user is "0600"
    owner: root
    path: /var/lib/AccountsService/users/ivan
    block: |
      [User]
      Languages=ru_RU.UTF-8;

- name: manage placeholder user that doesnt exist
  become_user: "testing"
  tags: [ never, testing ]
  block:
    - name: set GNOME dark style
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "prefer-dark"
        state: present
      ignore_errors: true # because it might fail in a weird way
