# DO NOT tag anything with "personal" because it inherits this tag
# also same applies to "home" tag. dont tag it :)

- name: manage my user-local configuration :)
  become_user: "{{ main_user }}"
  block:
    - name: set UK time format
      community.general.dconf:
        key: "/system/locale/region"
        value: "'en_GB.UTF-8'"
        state: present

    - name: fetch podman container images
      tags:
        - podman
      ignore_errors: true
      containers.podman.podman_image:
        name: "{{ item }}"
        state: present
      loop:
        - nginx: latest # debug
        - debian:12
        - opensuse/tumbleweed:latest
        - fedora:latest

    - name: create directories i # funni, iso, git\github
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/Desktop/github
        - ~/Desktop/git
        - ~/Pictures/funni
        - ~/Pictures/wallpapers
        - ~/Videos/funni

    - name: create directories with CoW disabled
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        attributes: '+C'
      loop:
        - ~/Downloads/iso
        - ~/Downloads/torrent
        - ~/Videos/torrent
        - ~/Music/torrent

    - name: fetch git repos with configs :)
      git:
        clone: true
        force: true
        update: true
        repo: https://github.com/allpower2slaves/dotfiles.git
        dest: ~/Desktop/github/dotfiles
      ignore_errors: true
      tags:
        - git

    - name: make symlinks and apply the config files
      file:
        src: "~/Desktop/github/dotfiles/{{ item }}"
        dest: "~/.config/{{ item }}"
        force: true
        state: link
      ignore_errors: true     # why? because symlinking may literally fail. i dont want to force rm firectories with ansible :)
      loop:
        - nvim
        - mpv
        - fish
        - ghostty

    - name: (dirty) apply generic cross-system GNOME settings # its not idempotent!!
      shell:
        cmd: |
          dconf load / < ~/Desktop/github/dotfiles/gnome-setup.dconf
      when: apply_dconf
      tags:
        - experimental

    - name: Make fedora-based texlive container for distrobox # maybe i should switch to alpine?
      containers.podman.podman_image:
        state: build
        name: fedora-texlive-distrobox
        build:
          cache: true
          container_file: |-
            FROM fedora:latest
            RUN dnf install -y texlive-scheme-full
            RUN dnf --setopt "install_weak_deps=False" install -y fish
      tags:
        - podman
        - latex # do i even need this tag at all

# end of block
