---
# since `dnf offline-upgrade download` and `dnf upgrade --downloadonly`
# apparently DONT share their cachedir and i dont want to add more cruft i just
# split these methods into two tasklists

- import_tasks:
    file: upgrade-classic.yaml
  when: mode != "offline-upgrade"
  tags:
    - dnf
    - upgrade

- import_tasks:
    file: upgrade-offline.yaml
  when: mode == "offline-upgrade"
  tags:
    - dnf
    - upgrade
    - reboot
    - experimental
