---
- name: Upgrade the system
  dnf:
    name: "*"
    state: latest
  tags:
    - dnf
    - upgrade


- name: Check if reboot required
  command: 'sudo dnf needs-restarting -r'
  register: dnf_upgrade_reboot_required
  ignore_errors: true
  changed_when: dnf_upgrade_reboot_required.rc != 0
  failed_when: false
  tags:
    - dnf
    - reboot
  notify: "reboot"

- name: Force flush
  meta: flush_handlers
  when: reboot_force
  tags:
    - reboot
